// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {llm} from '../models';

export function ActorCancel(arg1:string):Promise<desktop.ActorResult>;

export function ActorCleanup(arg1:number):Promise<number>;

export function ActorGet(arg1:string):Promise<desktop.ActorInfo>;

export function ActorList(arg1:string):Promise<Array<desktop.ActorInfo>>;

export function ActorSpawn(arg1:string,arg2:string,arg3:string):Promise<desktop.ActorResult>;

export function AddModel(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:Array<string>,arg8:string,arg9:number,arg10:number,arg11:number,arg12:boolean,arg13:boolean,arg14:boolean):Promise<void>;

export function AgentGetCurrent():Promise<desktop.AgentConfigInfo>;

export function AgentListConfigs():Promise<Array<desktop.AgentConfigInfo>>;

export function AgentSwitch(arg1:string):Promise<desktop.AgentSwitchResult>;

export function AgentUpdateConfig(arg1:string,arg2:desktop.AgentConfigInfo):Promise<desktop.AgentSwitchResult>;

export function CancelOperation():Promise<void>;

export function CompressContext():Promise<Record<string, number>>;

export function CreateCheckpoint(arg1:string):Promise<desktop.CheckpointResult>;

export function CreateNewSession(arg1:string):Promise<string>;

export function CreateWorkspace(arg1:string):Promise<desktop.WorkspaceDTO>;

export function DeleteCheckpoint(arg1:string):Promise<desktop.CheckpointResult>;

export function DeleteSession(arg1:string):Promise<void>;

export function DistillListCandidates():Promise<Array<desktop.SkillCandidateInfo>>;

export function DistillRun():Promise<desktop.DreamResult>;

export function DreamRun():Promise<desktop.DreamResult>;

export function ExportChat(arg1:Array<desktop.ExportMessage>):Promise<void>;

export function ExportCheckpoints():Promise<string>;

export function GetCheckpointSummary(arg1:string):Promise<string>;

export function GetConfig():Promise<desktop.AppConfigDTO>;

export function GetMCPServers():Promise<Array<desktop.MCPServerInfo>>;

export function GetModelName():Promise<string>;

export function GetTools():Promise<Array<desktop.ToolInfo>>;

export function GetVersion():Promise<Record<string, string>>;

export function GetWorkingDir():Promise<string>;

export function IsBusy():Promise<boolean>;

export function ListCheckpoints():Promise<Array<desktop.CheckpointInfo>>;

export function ListMemoryFiles():Promise<Array<desktop.MemoryFileInfo>>;

export function ListRemoteModels(arg1:string):Promise<Array<llm.ModelInfo>>;

export function ListRemoteModelsWithConfig(arg1:string,arg2:string):Promise<Array<llm.ModelInfo>>;

export function ListSessions(arg1:number):Promise<Array<desktop.SessionDTO>>;

export function ListWorkspaces():Promise<Array<desktop.WorkspaceDTO>>;

export function LoadSession(arg1:string):Promise<desktop.SessionData>;

export function MemoryCount():Promise<number>;

export function MemoryIndexFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function MemoryReconcile():Promise<number|number>;

export function MemorySearch(arg1:string,arg2:string,arg3:number):Promise<Array<desktop.MemorySearchResult>>;

export function MoveSession(arg1:string,arg2:string):Promise<void>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function ReadMemory(arg1:string):Promise<string>;

export function RemoveModel(arg1:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function RespondToConfirm(arg1:boolean):Promise<void>;

export function RespondToConfirmAll(arg1:boolean):Promise<void>;

export function RestoreCheckpoint(arg1:string):Promise<desktop.CheckpointResult>;

export function SaveSessionFromFrontend(arg1:string,arg2:Array<desktop.ChatMessageDTO>):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function SetDefaultModel(arg1:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetPermission(arg1:string):Promise<void>;

export function SetPlanningMode(arg1:string):Promise<void>;

export function SetReasoningLevel(arg1:string):Promise<void>;

export function SetSafetyLevel(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function TaskBlock(arg1:string,arg2:string):Promise<desktop.TaskResult>;

export function TaskCreate(arg1:string,arg2:string):Promise<desktop.TaskResult>;

export function TaskDelete(arg1:string):Promise<desktop.TaskResult>;

export function TaskDone(arg1:string,arg2:string):Promise<desktop.TaskResult>;

export function TaskGetEvents(arg1:string):Promise<Array<desktop.TaskEventInfo>>;

export function TaskList(arg1:string,arg2:boolean):Promise<Array<desktop.TaskInfo>>;

export function TaskStart(arg1:string,arg2:string,arg3:string):Promise<desktop.TaskResult>;

export function UpdateAdvancedSettings(arg1:desktop.AdvancedSettingsDTO):Promise<void>;

export function UpdateModel(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:Array<string>,arg8:string,arg9:number,arg10:number,arg11:number,arg12:boolean,arg13:boolean,arg14:boolean):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowIsMaximised():Promise<boolean>;

export function WindowMaximise():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WriteMemory(arg1:string,arg2:string):Promise<void>;
