// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddModel(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14) {
  return window['go']['desktop']['App']['AddModel'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
}

export function CancelOperation() {
  return window['go']['desktop']['App']['CancelOperation']();
}

export function CompressContext() {
  return window['go']['desktop']['App']['CompressContext']();
}

export function CreateNewSession() {
  return window['go']['desktop']['App']['CreateNewSession']();
}

export function DeleteSession(arg1) {
  return window['go']['desktop']['App']['DeleteSession'](arg1);
}

export function ExportChat(arg1) {
  return window['go']['desktop']['App']['ExportChat'](arg1);
}

export function GetConfig() {
  return window['go']['desktop']['App']['GetConfig']();
}

export function GetMCPServers() {
  return window['go']['desktop']['App']['GetMCPServers']();
}

export function GetModelName() {
  return window['go']['desktop']['App']['GetModelName']();
}

export function GetTools() {
  return window['go']['desktop']['App']['GetTools']();
}

export function GetVersion() {
  return window['go']['desktop']['App']['GetVersion']();
}

export function GetWorkingDir() {
  return window['go']['desktop']['App']['GetWorkingDir']();
}

export function IsBusy() {
  return window['go']['desktop']['App']['IsBusy']();
}

export function ListRemoteModels(arg1) {
  return window['go']['desktop']['App']['ListRemoteModels'](arg1);
}

export function ListRemoteModelsWithConfig(arg1, arg2) {
  return window['go']['desktop']['App']['ListRemoteModelsWithConfig'](arg1, arg2);
}

export function ListSessions(arg1) {
  return window['go']['desktop']['App']['ListSessions'](arg1);
}

export function LoadSession(arg1) {
  return window['go']['desktop']['App']['LoadSession'](arg1);
}

export function OpenInExplorer(arg1) {
  return window['go']['desktop']['App']['OpenInExplorer'](arg1);
}

export function RemoveModel(arg1) {
  return window['go']['desktop']['App']['RemoveModel'](arg1);
}

export function RenameSession(arg1, arg2) {
  return window['go']['desktop']['App']['RenameSession'](arg1, arg2);
}

export function RespondToConfirm(arg1) {
  return window['go']['desktop']['App']['RespondToConfirm'](arg1);
}

export function RespondToConfirmAll(arg1) {
  return window['go']['desktop']['App']['RespondToConfirmAll'](arg1);
}

export function SaveSessionFromFrontend(arg1, arg2) {
  return window['go']['desktop']['App']['SaveSessionFromFrontend'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['desktop']['App']['SelectDirectory']();
}

export function SendMessage(arg1) {
  return window['go']['desktop']['App']['SendMessage'](arg1);
}

export function SetDefaultModel(arg1) {
  return window['go']['desktop']['App']['SetDefaultModel'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['desktop']['App']['SetLanguage'](arg1);
}

export function SetPermission(arg1) {
  return window['go']['desktop']['App']['SetPermission'](arg1);
}

export function SetPlanningMode(arg1) {
  return window['go']['desktop']['App']['SetPlanningMode'](arg1);
}

export function SetReasoningLevel(arg1) {
  return window['go']['desktop']['App']['SetReasoningLevel'](arg1);
}

export function SetSafetyLevel(arg1) {
  return window['go']['desktop']['App']['SetSafetyLevel'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['desktop']['App']['SetTheme'](arg1);
}

export function UpdateModel(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14) {
  return window['go']['desktop']['App']['UpdateModel'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
}

export function WindowClose() {
  return window['go']['desktop']['App']['WindowClose']();
}

export function WindowIsMaximised() {
  return window['go']['desktop']['App']['WindowIsMaximised']();
}

export function WindowMaximise() {
  return window['go']['desktop']['App']['WindowMaximise']();
}

export function WindowMinimise() {
  return window['go']['desktop']['App']['WindowMinimise']();
}
