// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActorCancel(arg1) {
  return window['go']['desktop']['App']['ActorCancel'](arg1);
}

export function ActorCleanup(arg1) {
  return window['go']['desktop']['App']['ActorCleanup'](arg1);
}

export function ActorGet(arg1) {
  return window['go']['desktop']['App']['ActorGet'](arg1);
}

export function ActorList(arg1) {
  return window['go']['desktop']['App']['ActorList'](arg1);
}

export function ActorSpawn(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['ActorSpawn'](arg1, arg2, arg3);
}

export function AddModel(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14) {
  return window['go']['desktop']['App']['AddModel'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
}

export function AgentGetCurrent() {
  return window['go']['desktop']['App']['AgentGetCurrent']();
}

export function AgentListConfigs() {
  return window['go']['desktop']['App']['AgentListConfigs']();
}

export function AgentSwitch(arg1) {
  return window['go']['desktop']['App']['AgentSwitch'](arg1);
}

export function AgentUpdateConfig(arg1, arg2) {
  return window['go']['desktop']['App']['AgentUpdateConfig'](arg1, arg2);
}

export function CancelOperation() {
  return window['go']['desktop']['App']['CancelOperation']();
}

export function CompressContext() {
  return window['go']['desktop']['App']['CompressContext']();
}

export function CreateCheckpoint(arg1) {
  return window['go']['desktop']['App']['CreateCheckpoint'](arg1);
}

export function CreateNewSession(arg1) {
  return window['go']['desktop']['App']['CreateNewSession'](arg1);
}

export function CreateWorkspace(arg1) {
  return window['go']['desktop']['App']['CreateWorkspace'](arg1);
}

export function DeleteCheckpoint(arg1) {
  return window['go']['desktop']['App']['DeleteCheckpoint'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['desktop']['App']['DeleteSession'](arg1);
}

export function DistillListCandidates() {
  return window['go']['desktop']['App']['DistillListCandidates']();
}

export function DistillRun() {
  return window['go']['desktop']['App']['DistillRun']();
}

export function DreamRun() {
  return window['go']['desktop']['App']['DreamRun']();
}

export function ExportChat(arg1) {
  return window['go']['desktop']['App']['ExportChat'](arg1);
}

export function ExportCheckpoints() {
  return window['go']['desktop']['App']['ExportCheckpoints']();
}

export function GetCheckpointSummary(arg1) {
  return window['go']['desktop']['App']['GetCheckpointSummary'](arg1);
}

export function GetConfig() {
  return window['go']['desktop']['App']['GetConfig']();
}

export function GetMCPServers() {
  return window['go']['desktop']['App']['GetMCPServers']();
}

export function GetModelName() {
  return window['go']['desktop']['App']['GetModelName']();
}

export function GetTools() {
  return window['go']['desktop']['App']['GetTools']();
}

export function GetVersion() {
  return window['go']['desktop']['App']['GetVersion']();
}

export function GetWorkingDir() {
  return window['go']['desktop']['App']['GetWorkingDir']();
}

export function IsBusy() {
  return window['go']['desktop']['App']['IsBusy']();
}

export function ListCheckpoints() {
  return window['go']['desktop']['App']['ListCheckpoints']();
}

export function ListDirChildren(arg1) {
  return window['go']['desktop']['App']['ListDirChildren'](arg1);
}

export function ListMemoryFiles() {
  return window['go']['desktop']['App']['ListMemoryFiles']();
}

export function ListRemoteModels(arg1) {
  return window['go']['desktop']['App']['ListRemoteModels'](arg1);
}

export function ListRemoteModelsWithConfig(arg1, arg2) {
  return window['go']['desktop']['App']['ListRemoteModelsWithConfig'](arg1, arg2);
}

export function ListSessions(arg1) {
  return window['go']['desktop']['App']['ListSessions'](arg1);
}

export function ListWorkspaceFiles(arg1, arg2) {
  return window['go']['desktop']['App']['ListWorkspaceFiles'](arg1, arg2);
}

export function ListWorkspaces() {
  return window['go']['desktop']['App']['ListWorkspaces']();
}

export function LoadSession(arg1) {
  return window['go']['desktop']['App']['LoadSession'](arg1);
}

export function MemoryCount() {
  return window['go']['desktop']['App']['MemoryCount']();
}

export function MemoryIndexFile(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['App']['MemoryIndexFile'](arg1, arg2, arg3, arg4);
}

export function MemoryReconcile() {
  return window['go']['desktop']['App']['MemoryReconcile']();
}

export function MemorySearch(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['MemorySearch'](arg1, arg2, arg3);
}

export function MoveSession(arg1, arg2) {
  return window['go']['desktop']['App']['MoveSession'](arg1, arg2);
}

export function OpenInExplorer(arg1) {
  return window['go']['desktop']['App']['OpenInExplorer'](arg1);
}

export function ReadMemory(arg1) {
  return window['go']['desktop']['App']['ReadMemory'](arg1);
}

export function RemoveModel(arg1) {
  return window['go']['desktop']['App']['RemoveModel'](arg1);
}

export function RenameSession(arg1, arg2) {
  return window['go']['desktop']['App']['RenameSession'](arg1, arg2);
}

export function RespondToConfirm(arg1) {
  return window['go']['desktop']['App']['RespondToConfirm'](arg1);
}

export function RespondToConfirmAll(arg1) {
  return window['go']['desktop']['App']['RespondToConfirmAll'](arg1);
}

export function RestoreCheckpoint(arg1) {
  return window['go']['desktop']['App']['RestoreCheckpoint'](arg1);
}

export function SaveSessionFromFrontend(arg1, arg2) {
  return window['go']['desktop']['App']['SaveSessionFromFrontend'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['desktop']['App']['SelectDirectory']();
}

export function SendMessage(arg1, arg2) {
  return window['go']['desktop']['App']['SendMessage'](arg1, arg2);
}

export function SetDefaultModel(arg1) {
  return window['go']['desktop']['App']['SetDefaultModel'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['desktop']['App']['SetLanguage'](arg1);
}

export function SetPermission(arg1) {
  return window['go']['desktop']['App']['SetPermission'](arg1);
}

export function SetPlanningMode(arg1) {
  return window['go']['desktop']['App']['SetPlanningMode'](arg1);
}

export function SetReasoningLevel(arg1) {
  return window['go']['desktop']['App']['SetReasoningLevel'](arg1);
}

export function SetSafetyLevel(arg1) {
  return window['go']['desktop']['App']['SetSafetyLevel'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['desktop']['App']['SetTheme'](arg1);
}

export function TaskBlock(arg1, arg2) {
  return window['go']['desktop']['App']['TaskBlock'](arg1, arg2);
}

export function TaskCreate(arg1, arg2) {
  return window['go']['desktop']['App']['TaskCreate'](arg1, arg2);
}

export function TaskDelete(arg1) {
  return window['go']['desktop']['App']['TaskDelete'](arg1);
}

export function TaskDone(arg1, arg2) {
  return window['go']['desktop']['App']['TaskDone'](arg1, arg2);
}

export function TaskGetEvents(arg1) {
  return window['go']['desktop']['App']['TaskGetEvents'](arg1);
}

export function TaskList(arg1, arg2) {
  return window['go']['desktop']['App']['TaskList'](arg1, arg2);
}

export function TaskStart(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['TaskStart'](arg1, arg2, arg3);
}

export function UpdateAdvancedSettings(arg1) {
  return window['go']['desktop']['App']['UpdateAdvancedSettings'](arg1);
}

export function UpdateModel(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14) {
  return window['go']['desktop']['App']['UpdateModel'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
}

export function WindowClose() {
  return window['go']['desktop']['App']['WindowClose']();
}

export function WindowIsMaximised() {
  return window['go']['desktop']['App']['WindowIsMaximised']();
}

export function WindowMaximise() {
  return window['go']['desktop']['App']['WindowMaximise']();
}

export function WindowMinimise() {
  return window['go']['desktop']['App']['WindowMinimise']();
}

export function WriteMemory(arg1, arg2) {
  return window['go']['desktop']['App']['WriteMemory'](arg1, arg2);
}
