// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function AddModel(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<void>;

export function CancelOperation():Promise<void>;

export function CompressContext():Promise<Record<string, number>>;

export function CreateNewSession():Promise<string>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetConfig():Promise<desktop.AppConfigDTO>;

export function GetMCPServers():Promise<Array<desktop.MCPServerInfo>>;

export function GetModelName():Promise<string>;

export function GetTools():Promise<Array<desktop.ToolInfo>>;

export function GetVersion():Promise<Record<string, string>>;

export function GetWorkingDir():Promise<string>;

export function IsBusy():Promise<boolean>;

export function ListSessions(arg1:number):Promise<Array<desktop.SessionDTO>>;

export function LoadSession(arg1:string):Promise<desktop.SessionData>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function RemoveModel(arg1:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function RespondToConfirm(arg1:boolean):Promise<void>;

export function RespondToConfirmAll(arg1:boolean):Promise<void>;

export function SaveCurrentSession():Promise<void>;

export function SaveSessionFromFrontend(arg1:string,arg2:Array<desktop.ChatMessageDTO>):Promise<void>;

export function SendMessage(arg1:string):Promise<void>;

export function SetDefaultModel(arg1:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetPlanningMode(arg1:string):Promise<void>;

export function SetSafetyLevel(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowIsMaximised():Promise<boolean>;

export function WindowMaximise():Promise<void>;

export function WindowMinimise():Promise<void>;
