// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {llm} from '../models';

export function AddModel(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:Array<string>,arg8:string,arg9:number,arg10:number,arg11:number,arg12:boolean,arg13:boolean,arg14:boolean):Promise<void>;

export function CancelOperation():Promise<void>;

export function CompressContext():Promise<Record<string, number>>;

export function CreateNewSession(arg1:string):Promise<string>;

export function CreateWorkspace(arg1:string):Promise<desktop.WorkspaceDTO>;

export function DeleteSession(arg1:string):Promise<void>;

export function ExportChat(arg1:Array<desktop.ExportMessage>):Promise<void>;

export function GetConfig():Promise<desktop.AppConfigDTO>;

export function GetMCPServers():Promise<Array<desktop.MCPServerInfo>>;

export function GetModelName():Promise<string>;

export function GetTools():Promise<Array<desktop.ToolInfo>>;

export function GetVersion():Promise<Record<string, string>>;

export function GetWorkingDir():Promise<string>;

export function IsBusy():Promise<boolean>;

export function ListRemoteModels(arg1:string):Promise<Array<llm.ModelInfo>>;

export function ListRemoteModelsWithConfig(arg1:string,arg2:string):Promise<Array<llm.ModelInfo>>;

export function ListSessions(arg1:number):Promise<Array<desktop.SessionDTO>>;

export function ListWorkspaces():Promise<Array<desktop.WorkspaceDTO>>;

export function LoadSession(arg1:string):Promise<desktop.SessionData>;

export function MoveSession(arg1:string,arg2:string):Promise<void>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function RemoveModel(arg1:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function RespondToConfirm(arg1:boolean):Promise<void>;

export function RespondToConfirmAll(arg1:boolean):Promise<void>;

export function SaveSessionFromFrontend(arg1:string,arg2:Array<desktop.ChatMessageDTO>):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function SetDefaultModel(arg1:string):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetPermission(arg1:string):Promise<void>;

export function SetPlanningMode(arg1:string):Promise<void>;

export function SetReasoningLevel(arg1:string):Promise<void>;

export function SetSafetyLevel(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function UpdateModel(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:Array<string>,arg8:string,arg9:number,arg10:number,arg11:number,arg12:boolean,arg13:boolean,arg14:boolean):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowIsMaximised():Promise<boolean>;

export function WindowMaximise():Promise<void>;

export function WindowMinimise():Promise<void>;
