// Wails event listener helper
// @wailsio/runtime will be auto-generated by Wails, but we define a typed wrapper here

// Event name constants — keep in sync with desktop/events.go
export const EVENTS = {
  // Agent streaming
  THINKING: "agent:thinking",
  DELTA: "agent:delta",
  TOOL_CALL: "agent:toolcall",
  TOOL_RESULT: "agent:toolresult",
  USAGE: "agent:usage",
  ERROR: "agent:error",
  COMPRESSING: "agent:compressing",
  COMPRESS_DONE: "agent:compress_done",
  // Planning
  PLANNING: "agent:planning",
  PLAN_GENERATED: "agent:plan:generated",
  PLAN_STEP_START: "agent:plan:stepstart",
  PLAN_STEP_DONE: "agent:plan:stepdone",
  // Chat lifecycle
  CHAT_START: "chat:start",
  CHAT_DONE: "chat:done",
  CHAT_ERROR: "chat:error",
  CHAT_CANCELLED: "chat:cancelled",
  // Safety
  SAFETY_CONFIRM: "safety:confirm",
} as const;

type EventCallback = (...args: unknown[]) => void;

declare global {
  interface Window {
    runtime: {
      EventsOn: (eventName: string, callback: EventCallback) => () => void;
      EventsOff: (eventName: string) => void;
    };
  }
}

export function EventsOn(eventName: string, callback: EventCallback): () => void {
  if (window.runtime?.EventsOn) {
    return window.runtime.EventsOn(eventName, callback);
  }
  console.warn(`Wails runtime not available, event: ${eventName}`);
  return () => {};
}

export function EventsOff(eventName: string): void {
  if (window.runtime?.EventsOff) {
    window.runtime.EventsOff(eventName);
  }
}
